### ISSUE TITLE
Spacemouse support on Linux

### ISSUE THREAD

**Issue by dosssman** [vikashplus/vtils#4]
Hello again.

I have managed to get the spacemouse working on a Linux system without any changes to the code.
It was a bit tricky to get working, so I was wondering if you would be interested in a summary of the steps I followed.

Also, I am not sure in what format to add it if I were to do a PR.
Maybe adding the steps into the [comments in vtils/input/spacemouse.py](https://github.com/vikashplus/vtils/blob/94760713508b8e7982cbbb5f5e02a12c4efe6071/vtils/input/spacemouse.py#L11) ?Or into vtils README file ?

Thank you for your time.

**Comment by vikashplus** [comment]
This is amazing
- Let's start a README.md [here](https://github.com/vikashplus/vtils/tree/master/vtils/input) with details 
   - We can even move out the existing mac instructions to this readme.
   - We can also add a link in the [main readme](https://github.com/vikashplus/vtils/blob/master/README.md) as additional device and add a link to the detailed setup instructions. 
   WDYT?

**Comment by dosssman** [comment]
Thanks for the feedback !
Duly noted. I will follow the structure you suggested and open a PR and close the issue by the end of this week.

Best regards.
